CREATE TABLE `bookings` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(191) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`check_in` DATE NOT NULL,
	`check_out` DATE NOT NULL,
	`adult` SMALLINT(6) NULL DEFAULT NULL,
	`child` SMALLINT(6) NULL DEFAULT NULL,
	`infant` SMALLINT(6) NULL DEFAULT NULL,
	`nid` INT(11) NOT NULL,
	`passport` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`mobile` VARCHAR(191) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
